language: generic
services:
  - docker

before_install:
  - travis_wait 30 docker build -t phmclong/client_service ./client
  - travis_wait 30 docker build -t phmclong/nginx_service ./nginx
  - travis_wait 30 docker build -t phmclong/server_service ./server
  # Login to the docker CLI:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push phmclong/client_service 
  - docker push phmclong/nginx_service
  - docker push phmclong/server_service

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "micro_services"
  env: "Microservices-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-214620684615"
  bucket_path: "microservices"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
