export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATION_SUGGESTED_SEATS = 'GET_RESERVATION_SUGGESTED_SEATS';
export const SELECT_RESERVATIONS = 'SELECT_RESERVATIONS';
export const SELECT_ALL_RESERVATIONS = 'SELECT_ALL_RESERVATIONS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';